# Generated by Django 6.0.6 on 2026-06-30 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('price', models.PositiveBigIntegerField()),
                ('max_quantity_per_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.storeprofile')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='OfferFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('SELLER', 'Seller Shipping'), ('PLATFORM', 'Platform Shipping')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('preparation_time_hours', models.PositiveIntegerField(default=0)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('store', 'variant'), name='unique_store_variant_offer'),
        ),
        migrations.AddConstraint(
            model_name='offerfulfillment',
            constraint=models.UniqueConstraint(fields=('offer', 'method'), name='unique_offer_shipping_method'),
        ),
    ]
