# Generated by Django 6.0.6 on 2026-06-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number', 'account_type'], name='accounts_us_phone_n_622c95_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('phone_number', 'account_type'), name='unique_user_per_phone_number_and_account_type'),
        ),
    ]
