# Generated by Django 6.0.6 on 2026-06-28 15:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('persian_name', models.CharField(max_length=255)),
                ('english_name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='brands/')),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['persian_name', 'english_name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('TEXT', 'Text'), ('LONG_TEXT', 'Long Text'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('SELECT', 'Select'), ('MULTI_SELECT', 'Multi Select')], max_length=30)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpecificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VariantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('persian_name', models.CharField(max_length=300)),
                ('english_name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300)),
                ('introduction', models.TextField(blank=True)),
                ('expert_review', models.TextField(blank=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('state', models.CharField(choices=[('INITIALIZE', 'Initialize'), ('READY_TO_PUBLISH', 'Ready to publish'), ('UNDER_REVIEW', 'Under review'), ('NEED_EDIT', 'Need editing'), ('APPROVED', 'Approved')], max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.category')),
            ],
            options={
                'ordering': ['sort_order', 'persian_name', 'english_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('image', models.ImageField(upload_to='products/images/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.product')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=150, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.product')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('image', models.ImageField(upload_to='variants/images/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.productvariant')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.product')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.specification')),
            ],
            options={
                'ordering': ['specification'],
            },
        ),
        migrations.CreateModel(
            name='CategorySpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.category')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.specification')),
            ],
        ),
        migrations.AddField(
            model_name='specification',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.specificationgroup'),
        ),
        migrations.CreateModel(
            name='SpecificationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.specification')),
            ],
            options={
                'ordering': ['sort_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('display_value', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('variant_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.variantgroup')),
            ],
            options={
                'ordering': ['sort_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariantGroupValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.productvariant')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.variant')),
                ('variant_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogs.variantgroup')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryVariantGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.category')),
                ('variant_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.variantgroup')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.category')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('category', 'brand'), name='unique_category_brand')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='catalogs_pr_slug_2a5747_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['persian_name', 'english_name'], name='catalogs_pr_persian_38acf0_idx'),
        ),
        migrations.AddConstraint(
            model_name='productspecification',
            constraint=models.UniqueConstraint(fields=('product', 'specification'), name='unique_product_specification'),
        ),
        migrations.AddConstraint(
            model_name='categoryspecification',
            constraint=models.UniqueConstraint(fields=('category', 'specification'), name='unique_category_specification'),
        ),
        migrations.AddConstraint(
            model_name='productvariantgroupvalue',
            constraint=models.UniqueConstraint(fields=('product_variant', 'variant_group'), name='unique_product_variant_group'),
        ),
        migrations.AddConstraint(
            model_name='categoryvariantgroup',
            constraint=models.UniqueConstraint(fields=('category', 'variant_group'), name='unique_category_variant_group'),
        ),
    ]
