# Generated by Django 6.0.6 on 2026-06-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('identifier', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('LOGIN_CUSTOMER', 'Login Customer'), ('SIGNUP_CUSTOMER', 'SingUp Customer')], max_length=50)),
                ('code', models.CharField(max_length=255)),
                ('is_used', models.BooleanField(default=False)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['identifier', 'purpose'], name='otp_otp_identif_3c3d08_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_used', False)), fields=('identifier', 'purpose'), name='unique_active_otp_per_identifier_and_purpose')],
            },
        ),
    ]
