# Generated by Django 6.0.6 on 2026-06-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('LOGIN_CUSTOMER', 'Login Customer'), ('SIGNUP_CUSTOMER', 'SingUp Customer'), ('LOGIN_SELLER', 'Login Seller'), ('SIGNUP_SELLER', 'SingUp Seller')], max_length=50),
        ),
    ]
